### ISSUE TITLE
Pink Clouds

### ISSUE THREAD

**Issue by Cy4nX** [RangeMachine/KerbalVisualEnhancements#1]
The clouds are all pink! I have KerbalVisualEnhancements v1.0.3 installed on the 1.2 prerelease.
[images](http://imgur.com/a/yXbZx)

**Comment by RangeMachine** [comment]
Give me your KSP.log please. Did you tried another versions?

**Comment by Cy4nX** [comment]
Here are the relevant bits:
[LOG 13:08:16.136] Load(Texture): BoulderCo/Clouds/Textures/detail1
[LOG 13:08:16.222] Load(Texture): BoulderCo/Clouds/Textures/detaileve1
[LOG 13:08:16.289] Load(Texture): BoulderCo/Clouds/Textures/duna1
[LOG 13:08:16.419] Load(Texture): BoulderCo/Clouds/Textures/eve1
[LOG 13:08:16.531] Load(Texture): BoulderCo/Clouds/Textures/jool1
[LOG 13:08:16.648] Load(Texture): BoulderCo/Clouds/Textures/joolLayers1
[LOG 13:08:16.727] Load(Texture): BoulderCo/Clouds/Textures/joolLayers2
[LOG 13:08:16.794] Load(Texture): BoulderCo/Clouds/Textures/kerbin1
[LOG 13:08:18.736] Load(Texture): BoulderCo/Clouds/Textures/particle/1
[LOG 13:08:18.742] Load(Texture): BoulderCo/Clouds/Textures/particle/2
[LOG 13:08:18.748] Load(Texture): BoulderCo/Clouds/Textures/particle/3

[LOG 13:08:32.862] Config(CLOUDS_SETTINGS) BoulderCo/Clouds/CloudLayers/CLOUDS_SETTINGS
[LOG 13:08:32.862] Config(CLOUD_LAYER_PACK) BoulderCo/Clouds/CloudLayers/CLOUD_LAYER_PACK

[LOG 13:08:14.699] Load(Assembly): KerbalVisualEnhancements/Plugins/Clouds
[LOG 13:08:14.701] AssemblyLoader: Loading assembly at /Users/cy4n/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KerbalVisualEnhancements/Plugins/Clouds.dll
[LOG 13:08:14.741] Load(Assembly): KerbalVisualEnhancements/Plugins/Geometry
[LOG 13:08:14.741] AssemblyLoader: Loading assembly at /Users/cy4n/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KerbalVisualEnhancements/Plugins/Geometry.dll
[LOG 13:08:14.742] Load(Assembly): KerbalVisualEnhancements/Plugins/Utilities
[LOG 13:08:14.742] AssemblyLoader: Loading assembly at /Users/cy4n/Library/Application Support/Steam/steamapps/common/Kerbal Space Program/GameData/KerbalVisualEnhancements/Plugins/Utilities.dll
KerbalVisualEnhancements
[LOG 13:08:32.865] Config(KERBAL_VISUAL_ENHANCEMENTS) KerbalVisualEnhancements/Settings/KERBAL_VISUAL_ENHANCEMENTS

**Comment by RangeMachine** [comment]
Give me full log please, you can paste it here [http://pastebin.com/](url)

**Comment by Cy4nX** [comment]
http://pastebin.com/Zn0pCw0T

**Comment by Cy4nX** [comment]
Yes, I also tried 1.0.2

**Comment by RangeMachine** [comment]
Yes, there was problem with shaders on OpenGL renderer, uploading update now.

**Comment by Cy4nX** [comment]
THANK YOU!!!

**Comment by RangeMachine** [comment]
[Update](https://github.com/RangeMachine/KerbalVisualEnhancements/releases/tag/v1.0.4). Check it and let me know works it or not please.

**Comment by Cy4nX** [comment]
IT WORKED! http://i.imgur.com/zhqHSQ9.jpg

**Comment by RangeMachine** [comment]
Good to hear it :+1:
